import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
[env]
TERM = "xterm-256color"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
size = 12.0

[keyboard]
bindings = [
    { key="Up", mods="Control|Shift", action="ScrollLineUp" },
    { key="Down", mods="Control|Shift", action="ScrollLineDown" },
]
