import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
[env]
TERM = "xterm-256color"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
    size = 12.0

    [font.bold]
        family = "FiraCode Nerd Font"
        style  = "Bold"

    [font.bold_italic]
        family = "FiraCode Nerd Font"
        style  = "Bold Italic"

    [font.glyph_offset]
        x = 0
        y = 0

    [font.italic]
        family = "FiraCode Nerd Font"
        style  = "Italic"

    [font.normal]
        family = "FiraCode Nerd Font"
        style  = "Regular"

    [font.offset]
        x = 0
        y = 0

[keyboard]
bindings = [
    { key="Up", mods="Control|Shift", action="ScrollLineUp" },
    { key="Down", mods="Control|Shift", action="ScrollLineDown" },
]

