# Options to make tmux more pleasant
set -g mouse on
# set -g default-terminal "tmux-256color"
# bind-key I display-message "Installing plugins..." \; run-shell "~/.config/tmux/plugins/tpm/bin/install_plugins"
set-option -g status-position top
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set-option -g update-environment "OPENAI_API_KEY"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'nordtheme/nord-tmux'
set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
