#Define WS Vars
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

workspace $ws1 output $primarymonitor
workspace $ws2 output $primarymonitor
workspace $ws3 output $primarymonitor
workspace $ws4 output $primarymonitor
workspace $ws5 output $primarymonitor
workspace $ws6 output $primarymonitor

workspace $ws7 output $secondarymonitor
workspace $ws8 output $secondarymonitor
workspace $ws9 output $secondarymonitor
workspace $ws10 output $secondarymonitor
